name: google_maps_flutter_heatmap
description: A Flutter plugin for integrating Google Maps in iOS and Android applications. with heatmap support
homepage: https://github.com/bmabir17/google_maps_flutter_heatmap
version: 0.1.1+3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # TODO(iskakaushik): The following dependencies can be removed once
  # https://github.com/dart-lang/pub/issues/2101 is resolved.
  flutter_driver:
    sdk: flutter
  test: ^1.6.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlemaps
        pluginClass: GoogleMapsPlugin
      ios:
        pluginClass: FLTGoogleMapsPlugin

environment:
  sdk: ">=2.0.0-dev.47.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
